### ISSUE TITLE
 Build step io.quarkus.cxf.deployment.QuarkusCxfProcessor#createBeans threw an exception: java.lang.NoClassDefFoundError: io/quarkus/deployment/util/HashUtil

### ISSUE THREAD

**Issue by turchinc** [shumonsharif/quarkus-cxf#3]
I am trying to create a simple stub SOAP server for testing with one simple method:
```
package com.svr.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

@WebService
public interface Service {

    @WebMethod
    public void runScript(
        @WebParam(name = "runScriptParameters", targetNamespace = "")
        com.adobe.ns.indesign.soap.RunScriptParameters runScriptParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorNumber", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> errorNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorString", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> errorString,
        @WebParam(mode = WebParam.Mode.OUT, name = "scriptResult", targetNamespace = "")
        javax.xml.ws.Holder<com.adobe.ns.indesign.soap.Data> scriptResult
    );
}
```
The IDE seems to think everything is OK and `gradle jar` also builds my code, but when I do `gradlew assemble`  I get this:
```
PS C:\indd-svr-stub> .\gradlew assemble

> Task :quarkusPrepare
preparing quarkus application

> Task :quarkusBuild FAILED
building quarkus jar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.cxf.deployment.QuarkusCxfProcessor#createBeans threw an exception: java.lang.NoClassDefFoundError: io/quarkus/deployment/util/HashUtil
        at io.quarkus.cxf.deployment.QuarkusCxfProcessor.createProducer(QuarkusCxfProcessor.java:1294)
        at io.quarkus.cxf.deployment.QuarkusCxfProcessor.createBeans(QuarkusCxfProcessor.java:1275)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
  Caused by: java.lang.ClassNotFoundException: io.quarkus.deployment.util.HashUtil
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:426)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:363)
        ... 14 more


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
5 actionable tasks: 3 executed, 2 up-to-date
PS C:\indd-svr-stub>
```

my build.gradle
```
plugins {
    id 'java'
    id 'io.quarkus' version "${quarkusVersion}"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = 'http://repo.maven.apache.org/maven2'
    }
}

dependencies {
    implementation 'io.quarkus:quarkus-jaxb'
    implementation enforcedPlatform("io.quarkus:quarkus-universe-bom:${quarkusVersion}")
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'io.quarkus:quarkus-undertow'
    implementation "com.github.shumonsharif:quarkus-cxf:1.0.0-alpha-01"
    implementation 'jakarta.xml.ws:jakarta.xml.ws-api:2.3.3'
    implementation 'jakarta.jws:jakarta.jws-api:2.1.0'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

```
quarkusVersion is set to `quarkusVersion=1.7.0.Final`

This is my first foray with quarkus so could be my problem, do you see anything wrong? Thanks.

Update: just tried a simple a simple "hello-gradle" rest service  without cxf using resteasy and it builds fine.

**Comment by turchinc** [comment]
Same thing for me in mvn:
```
C:\hello-maven\> mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------------< bi.test:indd-stub >--------------------------
[INFO] Building indd-stub 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.7.0.Final:prepare (default) @ indd-stub ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ indd-stub ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ indd-stub ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- quarkus-maven-plugin:1.7.0.Final:prepare-tests (default) @ indd-stub ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ indd-stub ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\hello-maven\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ indd-stub ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ indd-stub ---
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ indd-stub ---
[INFO] Building jar: C:\hello-maven\target\indd-stub-1.0.0-SNAPSHOT.jar
[INFO]
[INFO] --- quarkus-maven-plugin:1.7.0.Final:build (default) @ indd-stub ---
[INFO] [org.jboss.threads] JBoss Threads version 3.1.1.Final
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.029 s
[INFO] Finished at: 2020-08-20T18:43:40+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.7.0.Final:build (default) on project indd-stub: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.cxf.deployment.QuarkusCxfProcessor#createBeans threw an exception: java.lang.NoClassDefFoundError: io/quarkus/deployment/util/HashUtil
[ERROR]         at io.quarkus.cxf.deployment.QuarkusCxfProcessor.createProducer(QuarkusCxfProcessor.java:1294)
[ERROR]         at io.quarkus.cxf.deployment.QuarkusCxfProcessor.createBeans(QuarkusCxfProcessor.java:1275)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.lang.ClassNotFoundException: io.quarkus.deployment.util.HashUtil
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:428)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:363)
[ERROR]         ... 14 more
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by gastaldi** [comment]
This PR makes this extension compatible with 1.7.x.Final onwards: https://github.com/shumonsharif/quarkus-cxf/pull/4
