### ISSUE TITLE
native build fails 

### ISSUE THREAD

**Issue by LorenzoBono** [shumonsharif/quarkus-cxf#6]
I have a class in my GRPC quarkus project from which I want to make a SOAP call. For this purpose I included the "com.github.shumonsharif" LIB.

But I have bugs in the native build. For debugging I made a new project which contains only the maven import except for an empty implemented shell class.
 
Nevertheless I have fixed the bugs in the native build

@Singleton
@RegisterForReflection
public class SubmitService extends MutinySubmitTransactionServiceGrpc.SubmitTransactionServiceImplBase {

}

mvn clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.container-image.registry=nfrt-docker-staging-local.repo.pnet.ch -Dquarkus.container-image.tag=latest

`Error: Unsupported features in 11 methods
Detailed message:
Error: Class initialization of com.sun.xml.bind.v2.runtime.output.FastInfosetStreamWriterOutput failed. Use the option --initialize-at-run-time=com.sun.xml.bind.v2.runtime.output.FastInfosetStreamWriterOutput to explicitly request delayed initialization of this class.
Original exception that caused the problem: java.lang.NoClassDefFoundError: org/jvnet/fastinfoset/VocabularyApplicationData
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at jdk.unsupported/sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:698)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:169)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:586)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:132)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.shouldInitializeAtRuntime(ConfigurableClassInitialization.java:155)
	at com.oracle.svm.hosted.snippets.ReflectionPlugins.processForName(ReflectionPlugins.java:167)
	at com.oracle.svm.hosted.snippets.ReflectionPlugins.access$000(ReflectionPlugins.java:62)
	at com.oracle.svm.hosted.snippets.ReflectionPlugins$1.apply(ReflectionPlugins.java:94)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.execute(InvocationPlugin.java:213)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.tryInvocationPlugin(BytecodeParser.java:2203)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1917)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1682)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1662)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5340)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3423)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3230)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1088)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.parseAndInlineCallee(BytecodeParser.java:2612)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.inline(BytecodeParser.java:2510)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.tryInline(BytecodeParser.java:2248)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1925)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1682)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1662)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5340)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3423)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3230)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1088)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:982)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
	at com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.getStaticInitializerGraph(UnsafeAutomaticSubstitutionProcessor.java:929)
	at com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.computeSubstitutions(UnsafeAutomaticSubstitutionProcessor.java:345)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:232)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:264)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:205)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:182)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(AnalysisMethod.java:108)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(AnalysisUniverse.java:412)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:400)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupMethod(WrappedConstantPool.java:116)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupMethodInPool(BytecodeParser.java:4323)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.lookupMethodInPool(SharedGraphBuilderPhase.java:107)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:4317)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1659)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5340)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3423)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3230)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1088)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:982)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:225)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:352)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:322)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:373)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:530)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ClassNotFoundException: org.jvnet.fastinfoset.VocabularyApplicationData
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 74 more
Error: Class initialization of org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor failed. Use the option --initialize-at-run-time=org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor to explicitly request delayed initialization of this class.
Original exception that caused the problem: java.lang.NoClassDefFoundError: javax/xml/soap/SOAPException
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)`

**Comment by dufoli** [comment]
Hmm need to add FastInfosetStreamWriterOutput  in UnremovableBeanBuildItem
unremovableBeans.produce(new UnremovableBeanBuildItem(
                                    new UnremovableBeanBuildItem.BeanClassNamesExclusion("com.sun.xml.bind.v2.runtime.output.FastInfosetStreamWriterOutput")));

if it is used in reflection maybe you need ReflectiveClassBuildItem too.

**Comment by dufoli** [comment]
it must be added in QuarkusCxfProcessor

**Comment by dufoli** [comment]
I have advance a lot but discover a bug in gizmo https://github.com/quarkusio/gizmo/issues/57 that block CXF native support

**Comment by dufoli** [comment]
I have fix not generated anotation value with 
/*classCreator.addAnnotation(AnnotationInstance.create(
                    DotName.createSimple(XmlAccessorType.class.getName()), null,
                    new AnnotationValue[]{AnnotationValue.createEnumValue("value",
                            DotName.createSimple( "javax.xml.bind.annotation.XmlAccessType"),
                                    "FIELD")}));
            */
            AnnotationCreator ac = classCreator.addAnnotation(XmlAccessorType.class.getName());
            ac.addValue("value", javax.xml.bind.annotation.XmlAccessType.FIELD);
but writer do not support it so it make compilation failed. Wait for fix in gizmo before going further.

**Comment by LorenzoBono** [comment]
ok, thanks for cara about

**Comment by dufoli** [comment]
commented part is not fix currently on gizmo master but I have sent a pull request to fix it.
https://github.com/quarkusio/gizmo/pull/59

uncommented part of my previous comment has been fixed on master with https://github.com/quarkusio/gizmo/pull/58

So now have to wait merge and release of gizmo to go further on native support.
A solution can be to implement annotation on function gettter instead of field.
As explain here :
https://stackoverflow.com/questions/12392235/illegalannotationsexception-class-has-two-properties-of-same-name

**Comment by dufoli** [comment]
PR 59 is merged. I have worked on bypass by moving attribute to getter on my branch.
but I have still another issue with native. We have schema namespace wich must be equal to "http://www.w3.org/2001/XMLSchema"
SChema is generated by reflexion. So issue come from generated class namespace I guess.

exception:
java.lang.RuntimeException: Invalid schema document passed to AbstractDataBinding.addSchemaDocument, not in W3C schema namespace: schema
	at org.apache.cxf.databinding.AbstractDataBinding.addSchemaDocument(AbstractDataBinding.java:111)
	at org.apache.cxf.databinding.AbstractDataBinding.addSchemaDocument(AbstractDataBinding.java:97)
	at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:408)
	at org.apache.cxf.service.factory.AbstractServiceFactoryBean.initializeDataBindings(AbstractServiceFactoryBean.java:86)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromClass(ReflectionServiceFactoryBean.java:469)
	at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.buildServiceFromClass(JaxWsServiceFactoryBean.java:693)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:529)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:262)
	at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:199)
	at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:103)
	at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:168)
	at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:211)
	at io.quarkus.cxf.CXFQuarkusServlet.loadBus(CXFQuarkusServlet.java:85)

**Comment by dufoli** [comment]
Hello, I need help, can someone use 
https://cxf.apache.org/docs/java-to-wsdl.html
or 
https://cxf.apache.org/docs/java-to-ws.html
to generate wrapperbean.
You can use integration-test class for that. else any other can be usefull.
Goal is to see what is generated class expected because I have generated it for native (not realtime generation possible) but I need to compare with expected generated class.

**Comment by shumonsharif** [comment]
@dufoli Please see attached
[GreetingWebServiceService.wsdl.txt](https://github.com/shumonsharif/quarkus-cxf/files/5388687/GreetingWebServiceService.wsdl.txt)

**Comment by shumonsharif** [comment]
@dufoli Please see attached ... 
[wrapperbeans.zip](https://github.com/shumonsharif/quarkus-cxf/files/5388708/wrapperbeans.zip)

**Comment by dufoli** [comment]
thanks, as expected namespace was not ok. I have fixed it.

**Comment by dufoli** [comment]
I have gone further but I have still some issue.

find a loader from ProxyClassLoader cache with interfaces [com.sun.xml.bind.marshaller.CharacterEscapeHandler sun.misc.Launcher$AppClassLoader@392a2d8] but can't see all interfaces

de ce que je vois ca vient de 
https://github.com/apache/cxf/blob/master/core/src/main/java/org/apache/cxf/common/util/ProxyClassLoaderCache.java
et 
https://github.com/apache/cxf/blob/2424d912e92109c3ce08a95347056e825b52c035/core/src/main/java/org/apache/cxf/common/util/ProxyHelper.java
je sais pas pourquoi le class loader voit pas les interfaces...

**Comment by dufoli** [comment]
main issue is exception because schema namespace is not ok but I try to fix previous exception / message not présent on jvm part because native issue can cme from that.

java.lang.RuntimeException: Invalid schema document passed to AbstractDataBinding.addSchemaDocument, not in W3C schema namespace: schema
	at org.apache.cxf.databinding.AbstractDataBinding.addSchemaDocument(AbstractDataBinding.java:111)
	at org.apache.cxf.databinding.AbstractDataBinding.addSchemaDocument(AbstractDataBinding.java:97)
	at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:408)
	at org.apache.cxf.service.factory.AbstractServiceFactoryBean.initializeDataBindings(AbstractServiceFactoryBean.java:86)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromClass(ReflectionServiceFactoryBean.java:469)
	at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.buildServiceFromClass(JaxWsServiceFactoryBean.java:693)

**Comment by dufoli** [comment]
I get the log of it.
DOCUMENT :<?xml version="1.0" encoding="UTF-8" standalone="no"?><schema xmlns:tns="http://cxf.it.quarkus.io/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://cxf.it.quarkus.io/" version="1.0">
<element name="reply" type="tns:reply"/>
<element name="replyResponse" type="tns:replyResponse"/>
<complexType name="reply"><sequence><element minOccurs="0" name="text" type="xs:string"/></sequence></complexType>
<complexType name="replyResponse"><sequence><element minOccurs="0" name="return" type="xs:string"/></sequence></complexType>
</schema>

I think it come from missing 
elementFormDefault="qualified
so it come from missing package-info loading .....

**Comment by dufoli** [comment]
I gone further ...
d.getDocumentElement() return an empty element. It must come from parsing issue with reflection used in it .
it seems to come from jaxp , So I will add jaxp extention and enrich with more reflection.

**Comment by dufoli** [comment]
ok got it.
jaxbContextImpl use proxy with com.sun.xml.txw2.TypedXmlWriter
so function com.sun.xml.bind.v2.schemagen.xmlschema.Schema._namespace do not work in native.

order of call method:
JAXBUtils.generateJaxbSchemas
    XmlSchemaGenerator.write
        XmlSchemaGenerator.Namespace.writeTo
            com.sun.xml.bind.v2.schemagen.xmlschema.Schema._namespace
ContainerElement must invoke proxy

so it can come from proxy. I have added all missing proxy interface. but still not ok for moment... Do not know why.

**Comment by dufoli** [comment]
so namespace issue is because
com.sun.xml.txw2.TXW.getTagName
can not load the package to check XmlNamespace

**Comment by dufoli** [comment]
great news native is working in java 8. Now I need to debug java 11. It was a nightmare to found all issue and fix them.
I let the ticket open because, : 
- I need to fix java 11 native support
- I have to remove all jaxp/ jaxb stuff and produce a merge request on quarkus for that.

**Comment by shumonsharif** [comment]
@dufoli Thanks so much, this is indeed great news.  Please keep us posted if we can support in any way!

**Comment by dufoli** [comment]
it run on both java 8 and 11.
we have switch to quarkiverse repo.
https://github.com/quarkiverse/quarkiverse-cxf
let s close the ticket.
